### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by andrewhood125** [andrewhood125/OnDamanda#1]
To-Do
====

OnDamanda 1.0
-----------------------
- [x] Elaborate setup instructions.  
- [ ] Create setup process for first run. 
- [x] Package OnDamanda 2.0 for download and tag it.  
- [x] Make videobox responsive.  
- [x] Add Error checking for 0 videos.  
- [x] add link to preview video from insert page.  
- [x] Add Storage Space on website somewhere.  
- [ ] For recently viewed create another table last_viewed with a id as a foreign key to video id and a timestamp. This needs to be created when a video is inserted.  
- [x] Add directory by rating option.  
- [x] Add directory by runtime option.  
- [x] treat spaces as % in the search function.   
- [ ] Support users make a profile page. Favorite movies lile instant queue.  
- [x] add download button on info page.  
- [ ] Leader board of movies watched or amount of time?  
- [ ] Add started watching finished watching columns.  
- [ ] Add location that you left a video and able to resume at that point.  
- [ ] A profile queue to setup your personal playlist of movies that will autoplay.  
- [x] Upload video page. 
- [ ] Scraping Videos in a Collection should not remove season and episode data. 
- [ ] Video Edit Page to resemble watch page with blanks with placeholders for the type of data required. A Save button will send a AJAX request to insert data and fields will return to normal. 
- [x] Collection time added should be the most recent time added from a video within. It should not be updated with current time when a video is edited. 
- [x] Change Random to have a collection count as 1 and if selected randomly select a video in that collection. 
- [ ] Create admin backend
- [ ] Create schema in database to support extra features. Including user level, videos watched by user when the place in the video they are etc etc read above. 
- [x] Link images to video on home page
- [x] Link directory page table headers respective directory listing. 
- [x] Return home page to something similar to OnDamanda 0.1 sliding tiles with thumbnails. 
- [ ] My Favorite videos/collection sidebar
- [ ] Recently Viewed Sidebar
- [ ] Related Videos Sidebar
- [ ] Unfinished Videos in sidebar
- [ ] integrate the use of gravatar
- [x] Use config file to set where to look for disk_free_space()
- [x] Change text on buttons on edit page to submit, and get info. 
- [ ] Clarify between recentlyViewed and recenty Watched and use them both.
- [ ] include link to status of convert all. Disallow single conversions while converting all. Grey out insert of movies being converted and link to their status
- [x] make nav bar static top
- [x] update video edit page collection no change to the name of collection.  
- [ ] Dim the lights
- [x] When viewing a collection update last_viewed
- [ ] Add search via GET instead of POST

OnDamanda 2.0
----------------------- 
- [ ] Subtitle Support.  
- [ ] Software checks and alerts if not installed. (all requirements in Server Requirements)  
- [ ] Change the background color and scheme according to the color palette of the the images. (Similar to iTunes viewing an album).  
- [ ] fix upload page styles and make controller, remove upload from htaccess
- [ ] Move to Bootstrap 3
- [ ] Create parent table media which holds both collections and videos and other things?
- [ ] add tags for videos and collections
- [ ] Search bar will filter out movies that currently are being displayed on the screen and then query the database when enter is pushed  
- [ ] Create setup script that populates AddVideo with some open source content. 
- [ ] Update look and feel, especially edit video and collection page. 
- [ ] Mass select and edit, insert into collection, scrape. 
- [ ] Scrap CodeIgniter and move to custom framework
- [ ] Move to WebApp style no page changes. All Ajax
- [ ] installation recently viewed or a global recently viewed / watched / started. 

OnDamanda 3.0
------------------------
- [ ]  Make OnDamanda run as a daemon and serve pages on its own without the help of Apache and it's been used this far.
